export default {
    "works": [
        {
            "id": "25",
            "title": "Todo app",
            "img": "todo.png",
            "tags": ["React", "JS", "SCSS"],
            "category": "react",
            "description": "Simple To-Do app, made with React, uses a series of useState Hooks to keep track of the tasks state, as well as some mapping and filtering for the conditional rendering of tasks, depending on their state.",
            "demo": "https://todo-list-hitmaizer.vercel.app/",
            "code": "https://github.com/hitmaizer/todo-list",
            "link":  "",
        },
        
        {
            "id": "24",
            "title": "Random Quote Generator",
            "img": "quotes.png",
            "tags": ["React", "JS", "SCSS"],
            "category": "react",
            "description": "A simple quote generator made with React. Fetches data from an API, renders a random one, and we can look for more results from the same author with a click of the button.",
            "demo": "https://quote-generator-hitmaizer.vercel.app/",
            "code": "https://github.com/hitmaizer/quote-generator",
            "link":  "",
        },
        
        {
            "id": "22",
            "title": "Windbnb",
            "img": "windbnb.png",
            "tags": ["React", "JS", "SCSS"],
            "category": "react",
            "description": "A clone page of Airbnb, focused on dynamic rendering of components based on condition, through mapping and filtering of available data.",
            "demo": "https://windbnb-hitmaizer.vercel.app/",
            "code": "https://github.com/hitmaizer/windbnb",
            "link":  "",
        },
        
        {
            "id": "23",
            "title": "Input Components",
            "img": "inputcomponents.png",
            "tags": ["React", "JS", "SCSS"],
            "category": "react",
            "description": "A series of different renders of the same input component based on different properties given. Made as part of the Front End Developer path on devChallenges.io",
            "demo": "https://inputs-components-hitmaizer.vercel.app/",
            "code": "https://github.com/hitmaizer/inputs-components",
            "link":  "",
        },
        
        {
            "id": "1",
            "title": "Interior Consultant",
            "img": "interior.png",
            "tags": ["responsive", "HTML", "CSS"],
            "category": "responsive",
            "description": "A interior consultant frontpage as a part of the devChallenges Responsive Web Developer path",
            "demo": "https://interior-consultant-challenge-ktlfl7plu-hitmaizer.vercel.app/",
            "code": "https://github.com/hitmaizer/responsive-web-interior.consultant",
        },
        
        {
            "id": "2",
            "title": "Edie's Homepage",
            "img": "ediepage.png",
            "tags": ["responsive", "HTML", "CSS"],
            "category": "responsive",
            "description": "A whole page for a Design company concept, part of the devChallenges Responsive Web Developer path",
            "demo": "https://edie-homepage-hitmaizer.vercel.app/",
            "code": "https://github.com/hitmaizer/edie-homepage",
        },
        
        {
            "id": "3",
            "title": "Checkout Page",
            "img": "checkout.png",
            "tags": ["responsive", "HTML", "CSS"],
            "category": "responsive",
            "description": "A simple checkout page, developed as part od the Responsive Web Developer path on devChallenges.io",
            "demo": "https://responsive-checkout-hitmaizer.vercel.app/",
            "code": "https://github.com/hitmaizer/responsive-checkout",
        },
        
        {
            "id": "4",
            "title": "Button Components",
            "img": "buttons.png",
            "tags": ["React", "JS", "CSS-in-JS"],
            "category": "react",
            "description": "Several different renders of different states of the same button component",
            "demo": "https://btn-components-hitmaizer.vercel.app/",
            "code": "https://github.com/hitmaizer/btn-styledcomponents",
        },
        
        {
            "id": "5",
            "title": "Quizz Game",
            "img": "quizz.png",
            "tags": ["React", "JS", "SCSS"],
            "category": "react",
            "description": "A simple quizz game. Fetches 4 random questions from an API and then checks the results!",
            "demo": "https://quizz-react-hitmaizer.vercel.app/",
            "code": "https://github.com/hitmaizer/quizz-project",
        },
        
        {
            "id": "6",
            "title": "Tenzies Game",
            "img": "tenzies.png",
            "tags": ["React", "JS", "SCSS"],
            "category": "react",
            "description": "Simple Tenzies game developed as introduction to React. Part of a Scrimba course",
            "demo": "https://tenzies-nine.vercel.app/",
            "code": "https://github.com/hitmaizer/tenzies",
        },
        
        {
            "id": "7",
            "title": "Car Dashboard",
            "img": "carui.jpg",
            "tags": ["UI Design", "Figma", "UI/UX"],
            "category": "ui",
            "description": "Car Dashboard UI design as part of the DailyUI Challenge",
            "demo": "",
            "code": "",
            "link": "https://dribbble.com/shots/15440795-Car-Interface",
        },
        
        {
            "id": "8",
            "title": "SocialN UI/UX",
            "img": "socialN.png",
            "tags": ["UI Design", "Figma", "UI/UX"],
            "category": "ui",
            "description": "UI/UX Design for a social network App concept",
            "demo": "",
            "code": "",
            "link": "https://tinyurl.com/2p82jsp3",
        },
        
        {
            "id": "9",
            "title": "Job Listing",
            "img": "joblisting.jpg",
            "tags": ["UI Design", "Figma", "UI/UX"],
            "category": "ui",
            "description": "A job listing app, designed on Figma ",
            "demo": "",
            "code": "",
            "link": "https://dribbble.com/shots/15583721-Job-Listing",
        },
        
        {
            "id": "10",
            "title": "Business Card 2.0",
            "img": "arapp.jpeg",
            "tags": ["AR", "Unity", "C#"],
            "category": "other",
            "description": "Augmented Reality Android app. A fully interactive digital portfolio, developed as a university project.",
            "demo": "",
            "code": "",
            "link": "https://tinyurl.com/58km727h",
        },
        
        {
            "id": "11",
            "title": "Controller Generations",
            "img": "motiongraphics.png",
            "tags": ["Motion", "Graphics", "Adobe AE"],
            "category": "other",
            "description": "A motion graphics project that shows the different generations of console controllers.",
            "demo": "",
            "code": "",
            "link":  "https://tinyurl.com/bdh7htfv",
        },
        
        {
            "id": "12",
            "title": "e-Sports Article",
            "img": "article.png",
            "tags": ["Article", "Adobe", "InDesign"],
            "category": "other",
            "description": "An article about e-Sports, how it started, the competitive scene, the growth and future.",
            "demo": "",
            "code": "",
            "link":  "https://tinyurl.com/yckpwfsh",
        },
        
        {
            "id": "13",
            "title": "Page 404",
            "img": "page404.png",
            "tags": ["HTML", "CSS", "SCSS"],
            "category": "responsive",
            "description": "A simple 404 page.",
            "demo": "https://page-404-one.vercel.app/",
            "code": "https://github.com/hitmaizer/responsive-web-404",
            "link":  "",
        },
        
        {
            "id": "14",
            "title": "My Team Page",
            "img": "teampage.png",
            "tags": ["HTML", "CSS", "SCSS"],
            "category": "responsive",
            "description": "A simple team page as a part of devChallenges.io Responsive Web Developer path, challenging us to develop a specific image layout.",
            "demo": "https://responsive-web-team-page.vercel.app/",
            "code": "https://github.com/hitmaizer/responsive-web-teamPage",
            "link":  "",
        },
        
        {
            "id": "15",
            "title": "My Gallery",
            "img": "mygallery.png",
            "tags": ["HTML", "CSS", "SCSS"],
            "category": "responsive",
            "description": "A simple gallery page as a part of devChallenges.io Responsive Web Developer path, challenging us to develop a specific image layout.",
            "demo": "https://my-gallery-three.vercel.app/",
            "code": "https://github.com/hitmaizer/my-gallery",
            "link":  "",
        },
        
        {
            "id": "16",
            "title": "Recipe Page",
            "img": "recipe.png",
            "tags": ["HTML", "CSS", "SCSS"],
            "category": "responsive",
            "description": "A recipe page as a part of devChallenges.io Responsive Web Developer path.",
            "demo": "https://recipe-master-page.vercel.app/",
            "code": "https://github.com/hitmaizer/recipe-page-master",
            "link":  "",
        },
        
        {
            "id": "17",
            "title": "Dashboard",
            "img": "dashboard.jpg",
            "tags": ["UI Design", "Figma", "UI/UX"],
            "category": "ui",
            "description": "Stats analytics dashboard made for the DailyUI Challenge 018",
            "demo": "",
            "code": "",
            "link":  "https://dribbble.com/shots/15309826-Analytics-Dashboard",
        },
        {
            "id": "18",
            "title": "Activity Feed",
            "img": "activityfeed.jpg",
            "tags": ["UI Design", "Figma", "UI/UX"],
            "category": "ui",
            "description": "Concept of a social media Activity feed for the Daily UI challenge 047.",
            "demo": "",
            "code": "",
            "link":  "https://dribbble.com/shots/15552303-Activity-Feed",
        },
        {
            "id": "19",
            "title": "Leaderboard",
            "img": "leaderboard.png",
            "tags": ["UI Design", "Figma", "UI/UX"],
            "category": "ui",
            "description": "Leaderboard for a mobile app as part of the Daily UI Challenge 019.",
            "demo": "",
            "code": "",
            "link":  "https://dribbble.com/shots/15313098-Leaderboard",
        },
        {
            "id": "20",
            "title": "Location Tracker",
            "img": "deliver.jpg",
            "tags": ["UI Design", "Figma", "UI/UX"],
            "category": "ui",
            "description": "Concept Onboard + Location Tracker as part of the DailyUI Challenge 020",
            "demo": "",
            "code": "",
            "link":  "https://dribbble.com/shots/15323328-Location-Tracker",
        },
        {
            "id": "21",
            "title": "Boarding Pass",
            "img": "boarding.jpg",
            "tags": ["UI Design", "Figma", "UI/UX"],
            "category": "ui",
            "description": "Concept for a Flight company mobile app as part of the DailyUI Challenge number 24, a Boarding Pass!",
            "demo": "",
            "code": "",
            "link":  "https://dribbble.com/shots/15354250-Boarding-Pass",
        },
        
    ]
}