export default {
    "works": [
        {
            "id": "1",
            "title": "Interior Consultant",
            "img": "interior.png",
            "tags": ["responsive", "HTML", "CSS"],
            "category": "responsive",
            "description": "A interior consultant frontpage as a part of the devChallenges Responsive Web Developer path",
            "demo": "https://interior-consultant-challenge-ktlfl7plu-hitmaizer.vercel.app/",
            "code": "https://github.com/hitmaizer/responsive-web-interior.consultant",
        },
        
        {
            "id": "2",
            "title": "Edie's Homepage",
            "img": "ediepage.png",
            "tags": ["responsive", "HTML", "CSS"],
            "category": "responsive",
            "description": "A whole page for a Design company concept, part of the devChallenges Responsive Web Developer path",
            "demo": "https://edie-homepage-hitmaizer.vercel.app/",
            "code": "https://github.com/hitmaizer/edie-homepage",
        },
        
        {
            "id": "3",
            "title": "Checkout Page",
            "img": "checkout.png",
            "tags": ["responsive", "HTML", "CSS"],
            "category": "responsive",
            "description": "A simple checkout page, developed as part od the Responsive Web Developer path on devChallenges.io",
            "demo": "https://responsive-checkout-hitmaizer.vercel.app/",
            "code": "https://github.com/hitmaizer/responsive-checkout",
        },
        
        {
            "id": "4",
            "title": "Button Components",
            "img": "buttons.png",
            "tags": ["React", "JS", "CSS-in-JS"],
            "category": "react",
            "description": "Several different renders of different states of the same button component",
            "demo": "https://btn-components-hitmaizer.vercel.app/",
            "code": "https://github.com/hitmaizer/btn-styledcomponents",
        },
        
        {
            "id": "5",
            "title": "Quizz Game",
            "img": "quizz.png",
            "tags": ["React", "JS", "SCSS"],
            "category": "react",
            "description": "A simple quizz game. Fetches 4 random questions from an API and then checks the results!",
            "demo": "https://quizz-react.vercel.app/",
            "code": "https://github.com/hitmaizer/quizz-project",
        },
        
        {
            "id": "6",
            "title": "Tenzies Game",
            "img": "tenzies.png",
            "tags": ["React", "JS", "SCSS"],
            "category": "react",
            "description": "Simple Tenzies game developed as introduction to React. Part of a Scrimba course",
            "demo": "https://tenzies-nine.vercel.app/",
            "code": "https://github.com/hitmaizer/tenzies",
        },
        
        {
            "id": "7",
            "title": "Car Dashboard",
            "img": "carui.jpg",
            "tags": ["UI Design", "Figma", "UI/UX"],
            "category": "ui",
            "description": "Car Dashboard UI design as part of the DailyUI Challenge",
            "demo": "",
            "code": "",
            "link": "https://dribbble.com/shots/15440795-Car-Interface",
        },
        
        {
            "id": "8",
            "title": "SocialN UI/UX",
            "img": "socialN.png",
            "tags": ["UI Design", "Figma", "UI/UX"],
            "category": "ui",
            "description": "UI/UX Design for a social network App concept",
            "demo": "",
            "code": "",
            "link": "https://tinyurl.com/2p82jsp3",
        },
        
        {
            "id": "9",
            "title": "Job Listing",
            "img": "joblisting.jpg",
            "tags": ["UI Design", "Figma", "UI/UX"],
            "category": "ui",
            "description": "A job listing app, designed on Figma ",
            "demo": "",
            "code": "",
            "link": "https://dribbble.com/shots/15583721-Job-Listing",
        },
        
        {
            "id": "10",
            "title": "Business Card 2.0",
            "img": "arapp.jpeg",
            "tags": ["AR", "Unity", "C#"],
            "category": "other",
            "description": "Augmented Reality Android app. A fully interactive digital portfolio, developed as a university project.",
            "demo": "",
            "code": "",
            "link": "https://tinyurl.com/58km727h",
        },
        
        {
            "id": "11",
            "title": "Controller Generations",
            "img": "motiongraphics.png",
            "tags": ["Motion", "Graphics", "Adobe AE"],
            "category": "other",
            "description": "A motion graphics project that shows the different generations of console controllers.",
            "demo": "",
            "code": "",
            "link":  "https://tinyurl.com/bdh7htfv",
        },
        
        {
            "id": "12",
            "title": "e-Sports Article",
            "img": "article.png",
            "tags": ["Article", "Adobe", "InDesign"],
            "category": "other",
            "description": "An article about e-Sports, how it started, the competitive scene, the growth and future.",
            "demo": "",
            "code": "",
            "link":  "https://tinyurl.com/yckpwfsh",
        },
    ]
}